import "@/core/styles/globals.css";

import { type Metadata } from "next";
import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import Provider from "@/core/context/provider/provider";

export const metadata: Metadata = {
  title: "GhostPad",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <Provider>
      <html
        lang="en"
        className={`${inter.variable} ${inter.className} font-medium`}
        suppressHydrationWarning
      >
        <body>{children}</body>
      </html>
    </Provider>
  );
}
